name: Feature request
description: Suggest an idea for Crab Fit
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: Check to make sure someone hasn't already opened a similar [issue](https://github.com/GRA0007/crab.fit/issues).

  - type: textarea
    attributes:
      label: Proposed feature or solution
      description: A clear and concise description of what you want to happen and why.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives
      description: Give a clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional information
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
