export * from './detectBrowser'
export * from './makeClass'
export * from './unhyphenate'
export * from './convertTimesToDates'
export * from './calculateAvailability'
export * from './calculateRows'
export * from './calculateColumns'
